/// Generated by Flutter GetX Starter on 2022-04-03 18:58
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'refrence_screen_logic.dart';

class RefrenceScreenView extends StatelessWidget {
  final RefrenceScreenLogic logic = Get.put(RefrenceScreenLogic());

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}