/// Generated by Flutter GetX Starter on 2022-04-03 18:58
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'landing_screen_logic.dart';

class LandingScreenView extends StatelessWidget {
  final LandingScreenLogic logic = Get.put(LandingScreenLogic());

  LandingScreenView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [Text("Hello")],
    );
  }
}