/// Generated by Flutter GetX Starter on 2022-04-03 20:10
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'tools_screen_logic.dart';

class ToolsScreenView extends StatelessWidget {
  final ToolsScreenLogic logic = Get.put(ToolsScreenLogic());

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}