/// Generated by Flutter GetX Starter on 2022-04-03 19:34
import 'package:get/get.dart';


class OutputViewLogic extends GetxController {

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}