/// Generated by Flutter GetX Starter on 2022-04-03 18:59
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'assembler_screen_logic.dart';

class AssemblerScreenView extends StatelessWidget {
  final AssemblerScreenLogic logic = Get.put(AssemblerScreenLogic());

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}